//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports {
    
    public partial class basketball_accessoriesandref {
        protected DirectSports.Controls.CustomControls.ProductLister plBasketballImages;
        protected DirectSports.Controls.UserControls.NoImageProductLister refList;
        protected System.Web.UI.HtmlControls.HtmlImage imgRefShirt;
    }
}
