//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports {
    
    public partial class requestinformation {
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.RegularExpressionValidator regEmail;
        protected System.Web.UI.WebControls.RequiredFieldValidator reqEmail;
        protected System.Web.UI.WebControls.Label lblRequest;
        protected System.Web.UI.WebControls.TextBox txtRequest;
        protected System.Web.UI.WebControls.Label lblSubmit;
        protected System.Web.UI.WebControls.Button btnRequestCatalogue;
        protected System.Web.UI.WebControls.Label lblCatalogueRequestResult;
    }
}
