//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports {
    
    public partial class requestcat {
        protected System.Web.UI.WebControls.CheckBoxList clSports;
        protected System.Web.UI.WebControls.Label lblName;
        protected System.Web.UI.WebControls.TextBox txtName;
        protected System.Web.UI.WebControls.Label lblAddress1;
        protected System.Web.UI.WebControls.TextBox txtAddress1;
        protected System.Web.UI.WebControls.Label lblAddress2;
        protected System.Web.UI.WebControls.TextBox txtAddress2;
        protected System.Web.UI.WebControls.Label lblAddress3;
        protected System.Web.UI.WebControls.TextBox txtAddress3;
        protected System.Web.UI.WebControls.Label lblPostcode;
        protected System.Web.UI.WebControls.TextBox txtPostcode;
        protected System.Web.UI.WebControls.Label lblSubmit;
        protected System.Web.UI.WebControls.Button btnRequestCatalogue;
        protected System.Web.UI.WebControls.Label lblCatalogueRequestResult;
    }
}
