//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports {
    
    public partial class basketball_trainingequipment {
        protected DirectSports.Controls.CustomControls.ProductLister plTrainingEquipment;
        protected DirectSports.Controls.UserControls.NoImageProductLister firstAidList;
        protected DirectSports.Controls.UserControls.NoImageProductLister accessoriesList;
    }
}
