//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports {
    
    public partial class basketball_trampolines {
        protected DirectSports.Controls.CustomControls.ProductLister plRound;
        protected DirectSports.Controls.CustomControls.ProductLister plCombination;
        protected DirectSports.Controls.UserControls.NoImageProductLister accessoriesList;
    }
}
