//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports.adminarea.MasterPages {
    
    public partial class DirectSportsAdmin {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Microsoft.Web.UI.ScriptManager scmScriptManager;
        protected System.Web.UI.WebControls.Literal litLoggedInMessage;
        protected System.Web.UI.WebControls.LoginStatus lstsAdminLoginStatus;
        protected System.Web.UI.WebControls.ContentPlaceHolder cphAdminContent;
    }
}
