//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports.adminarea {
    
    public partial class editproduct {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Literal litProductName;
        protected System.Web.UI.WebControls.Label lblProdId;
        protected System.Web.UI.WebControls.Label txtProdId;
        protected System.Web.UI.WebControls.Label lblProdName;
        protected System.Web.UI.WebControls.TextBox txtProdName;
        protected System.Web.UI.WebControls.Label lblProdDescription;
        protected System.Web.UI.WebControls.TextBox txtProdDescription;
        protected System.Web.UI.WebControls.Label lblExtraInformation;
        protected System.Web.UI.WebControls.TextBox txtExtraInformation;
        protected System.Web.UI.WebControls.Label lblProdPrice;
        protected System.Web.UI.WebControls.TextBox txtProdPrice;
        protected System.Web.UI.WebControls.Label lblPriceFrom;
        protected System.Web.UI.WebControls.CheckBox chkPriceIsFrom;
        protected System.Web.UI.WebControls.Label lblIncludesVat;
        protected System.Web.UI.WebControls.CheckBox chkIncludesVat;
        protected System.Web.UI.WebControls.Label lblVisible;
        protected System.Web.UI.WebControls.CheckBox chkVisible;
        protected System.Web.UI.WebControls.Label lblDeliveryPrice;
        protected System.Web.UI.WebControls.TextBox txtDeliveryPrice;
        protected System.Web.UI.WebControls.Label lblImageFile;
        protected System.Web.UI.WebControls.TextBox txtImageFileName;
        protected System.Web.UI.WebControls.Label lblUpdate;
        protected System.Web.UI.WebControls.Button btnUpdate;
    }
}
