<%@ Page Language="C#" MasterPageFile="~/adminarea/MasterPages/DirectSportsAdmin.Master"
    AutoEventWireup="true" Codebehind="productadmin.aspx.cs" Inherits="DirectSports.adminarea.productadmin" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>
<asp:Content ID="conProductAdmin" ContentPlaceHolderID="cphAdminContent" runat="server">
    <h1>Product Sections</h1>
    <asp:UpdatePanel ID="upProductSection" runat="server">
        <ContentTemplate>
            <div id="divProductSectionTreeArea">
                <asp:TreeView CssClass="Tree" ShowExpandCollapse="true" NodeStyle-CssClass="NodeStyle"
                    HoverNodeStyle-CssClass="NodeHoverStyle" RootNodeStyle-CssClass="NodeStyle RootNodeStyle"
                    ID="tvProductSections" runat="server" AutoGenerateDataBindings="False" ExpandDepth="1"
                    OnSelectedNodeChanged="tvProductSections_SelectedNodeChanged" NodeIndent="5">
                    <RootNodeStyle CssClass="NodeStyle RootNodeStyle" />
                    <NodeStyle CssClass="NodeStyle" />
                    <HoverNodeStyle CssClass="NodeHoverStyle" />
                </asp:TreeView>
            </div>
            <div id="divProductsInSectionList">
                <asp:Literal id="litProductSectionName" runat="server"></asp:Literal>
                <asp:GridView CssClass="DefaultGrid" GridLines="None" ID="gvProductList" runat="server"
                    AllowPaging="True" PageSize="20" AutoGenerateColumns="False" OnPageIndexChanging="gvProductList_PageIndexChanging"
                    OnRowDataBound="gvProductList_RowDataBound">
                    <EmptyDataTemplate>
                        No Products Found.
                    </EmptyDataTemplate>
                    <Columns>
                        <asp:BoundField AccessibleHeaderText="Product Name" DataField="Name" HeaderText="Product Name"
                            ReadOnly="True" />
                        <asp:TemplateField AccessibleHeaderText="Edit" HeaderText="Edit" ShowHeader="False">
                            <ControlStyle CssClass="lnkGridEdit" />
                            <ItemStyle HorizontalAlign="Center" />
                            <HeaderStyle HorizontalAlign="Center" />
                            <ItemTemplate>
                                <asp:LinkButton CommandArgument='<%# Eval("Id") %>' ID="lnkEdit" runat="server" CausesValidation="false"
                                    CommandName="EditProduct" Text="Edit"></asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <RowStyle CssClass="DefaultGridRow" />
                    <HeaderStyle CssClass="DefaultGridHeader" />
                    <AlternatingRowStyle CssClass="DefaultGridRowAlternate" />
                    <EmptyDataRowStyle CssClass="emptyRow" />
                </asp:GridView>
            </div>
            <asp:Button ID="btnUpdatePanel" runat="server" CssClass="hiddenButton" OnClick="btnUpdatePanel_Click"
                Text="Button" />
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
