//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSports.adminarea {
    
    public partial class productadmin {
        protected Microsoft.Web.UI.UpdatePanel upProductSection;
        protected System.Web.UI.WebControls.TreeView tvProductSections;
        protected System.Web.UI.WebControls.Literal litProductSectionName;
        protected System.Web.UI.WebControls.GridView gvProductList;
        protected System.Web.UI.WebControls.Button btnUpdatePanel;
    }
}
