//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI;

namespace DirectSports.adminarea {
    
    public partial class specialofferadmin {
        protected UpdatePanel upSpecialOffers;
        protected System.Web.UI.WebControls.Panel changeProductPanel;
        protected System.Web.UI.WebControls.Label pnlOfferNumber;
        protected System.Web.UI.WebControls.Label lblProductNameSearch;
        protected System.Web.UI.WebControls.TextBox txtProductName;
        protected System.Web.UI.WebControls.LinkButton btnSearchProducts;
        protected System.Web.UI.WebControls.RadioButtonList rblProductSearchResults;
        protected System.Web.UI.WebControls.Button btnOkChangeProduct;
        protected System.Web.UI.WebControls.Button btnCancelChangeProduct;
        protected System.Web.UI.WebControls.GridView gvProductList;
    }
}
